# This playbook installs additional nmap libraries and scripts.
#
# Copyright (c) 2014 Fabian Affolter <fab@fedoraproject.org>
#
# All rights reserved.
# This file is licensed under GPLv2, for more details check COPYING.
# 
# Usage: ansible-playbook nmap-scripts.yml -f 10

---
#- hosts: fsl_hosts
- hosts: 127.0.0.1
  connection: local
  user: root
  vars:
    # Development librarieres and script directly from nmap
    - libs: [tls.lua]
    - nse: [ssl-poodle.nse]
    # Third party sources need the full URL
    - nse2: ['https://raw.githubusercontent.com/b4ldr/nse-scripts/master/dns-sd.nse',
             'https://raw.githubusercontent.com/b4ldr/nse-scripts/master/dns-nsec-enum.nse',
             'https://raw.githubusercontent.com/fabaff/fsl-test-bench/master/fsl-tb-detect.nse',
             'https://raw.githubusercontent.com/SpiderLabs/Nmap-Tools/master/NSE/http-screenshot.nse',
             'https://github.com/hkm/nmap-nse-scripts/blob/master/http-wordpress-attachment.nse',
             'https://raw.githubusercontent.com/ileiva/Nmap/master/scripts/http-filedownload-exploiter.nse'
             'http://seclists.org/nmap-dev/2014/q3/att-493/http-vuln-cve-2014-6271.nse'
            ]

  tasks:
  - name: download nmap libraries from nmap
    get_url: url=https://svn.nmap.org/nmap/nselib/{{ item }}
             dest=/usr/share/nmap/nselib/{{ item }}
             mode=0644
    with_items: libs

  - name: download nmap scripts from nmap
    get_url: url=https://svn.nmap.org/nmap/scripts/{{ item }}
             dest=/usr/share/nmap/scripts/{{ item }}
             mode=0644
    with_items: nse

  - name: download nmap scripts from third party sources
    get_url: url={{ item }}
             dest=/usr/share/nmap/scripts/
             mode=0644
    with_items: nse2
 
  - name: update nmap database
    command: /usr/bin/nmap --script-updatedb
